# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Gan
tagline:          'Homepage'
description:      'The personal webpage of <a href="https://ganz2016.github.io/" target="_blank">Gan Zhang</a>.'
url:              https://ganz2016.github.io/
baseurl:          /

author:
  name:           'Gan Zhang'
  url:            https://ganz2016.github.io/

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://ganz2016.github.io/
